backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Productos"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nombre", name: "name", widget: "string"}
      - {label: "Descripción", name: "description", widget: "text"}
      - {label: "Precio", name: "price", widget: "string"}
      - {label: "Imagen", name: "image", widget: "image"}
